[General]
network = Net
resultdir-subdivision = false
sim-time-limit = 15000s

# Numero di run per ogni valore di m (totale: 80 run)
repeat = 20
seed-set = ${repetition}

# SOURCE CLASSE 1
*.source1.userClass = 1
*.source1.meanInterArrival = 2.5 #${m=1.0, 1.4, 2.0, 2.5}      
*.source1.batchMin = 1
*.source1.batchMax = 4                

# SOURCE CLASSE 2
*.source2.userClass = 2
*.source2.meanInterArrival = 2.5 #${m}    
*.source2.batchMin = 1
*.source2.batchMax = 3              

# SERVICE RULE
*.queue.a1 = 7
*.queue.b1 = 16
*.queue.a2 = 5
*.queue.b2 = 14

# SERVICE TIME
*.queue.sp1 = 0.1
*.queue.l1 = 1.0
*.queue.u1 = 3.92
*.queue.sp2 = 0.1
*.queue.l2 = 1.0
*.queue.u2 = 2.54

# VACATION
*.queue.sv = 0.2
*.queue.z = 2.0
*.queue.w = 3.8
*.queue.N = 20

# SET UP
*.queue.h = 1.0
